Module 3
Bedkow/node.js pull request #4
Opened 2023-09-19 11:27 UTC by Bedkow

tasks 1, 2, 3 done

2023-09-19 20:02 UTC, eduardhyan requested changes

2023-09-19 20:02 UTC, eduardhyan commented on module-3/task3.js
> +					"./txtdirectory/nodejs-m3.t3.txt",
When I first ran it, it failed. The issue was that "txtdirectory" wasn't included in the git repository. After cloning the repo, it wasn't automatically generated, so I had to create it manually. Kindly implement conditions to ensure that if the directory doesn't exist, the program will create it.

2023-09-20 11:08 UTC, Bedkow commented on module-3/task1.js
> +		for (let i = lis.length; i > 0; i--) {
For loop counting modified according to comment. Thanks!

2023-09-20 11:28 UTC, Bedkow commented on module-3/task3.js
> +					"./txtdirectory/nodejs-m3.t3.txt",
@eduardhyan the Node.js docs state that if the file does not exist, it gets created with the desired content. Please take a look:
https://nodejs.org/api/fs.html#fsappendfilepath-data-options-callback

2023-09-20 11:41 UTC, Bedkow commented on module-3/task3.js
> +					"./txtdirectory/nodejs-m3.t3.txt",
directory added with .gitkeep

2023-09-20 17:23 UTC, eduardhyan approved these changes

2023-09-23 15:32 UTC, merged