Module 4
Bedkow/node.js pull request #5
Opened 2023-09-23 15:33 UTC by Bedkow

2023-09-23 18:29 UTC, eduardhyan requested changes

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/services/public-holidays.service.test.ts
> +describe("Get a list of public holidays", () => {
First parameter passed to describe function usually indicates the component/service/class/function that is being tested. The common way of naming it is "MY_CLASS testing suite"
In this case I think you can simply name it "public-holidays service test suite" or even just "public holidays service"

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/services/public-holidays.service.test.ts
> +	it("checks if today is public holiday in DE", async () => {
I believe here you are validating if the function returns true or false. (`expect([true, false]).toContain(isPublicHoliday);`)
So let's name things as they are, `it("should return only boolean value")`

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/services/public-holidays.service.test.ts
> +		const nextPublicHolidays = await getNextPublicHolidays("DE");
I would recommend writing a new `describe` block for each of the functions.
So each `describe` is testing only one "service/class/function", also many programmers report that writing nested describes becomes unmanageable later, I partially agree with this idea, but would leave it up to you to decide.

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/e2e.test.ts
> +	describe("/IsTodayPublicHoliday/DE", () => {
I recommend reading the nested describe statements article written by Kent C. Dodds. 
Personally I try to avoid them as much as I can.
https://kentcdodds.com/blog/avoid-nesting-when-youre-testing

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/helpers.test.ts
> +		}).toThrow(new Error(`Year provided not the current, received: 5023`));
A test should fail for only one reason. This test validates too many aspects; it checks a case where the function fails and a case where the function returns a valid response. This should not be the case with unit tests. Please separate and divide tests based on "what they test." If they examine all the valid cases, group them together. If they test error cases, group them together as well.

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/helpers.test.ts
> +	it("shortens public holiday entry", () => {
Why don't we test cases when a function receives an object that does not follow the expected schema? Or if it receives undefined instead of an object?

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/helpers.test.ts
> +	it("validates year '2023'", () => {
The test description is unfinished. A developer should understand what the function is doing and what is being tested within it. From the current description, it is understood that the function validates the '2023' string. However, this information is insufficient. There are lingering questions such as: 
1. What aspects does it validate? The 'Format', 'Length', 'Type of the variable', or does it 'Compare to something'?
2. A better approach would be to start with `it(should ...)`

I propose revising the description to: "It should return true if the provided argument is a valid number."

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/helpers.test.ts
> +	it("validates year '2023'", () => {
Following this, I recommend testing also invalid cases.

2023-09-23 18:29 UTC, eduardhyan commented on module-4/src/e2e.test.ts
> +			expect(body.length).toBeGreaterThan(0);
I believe you can also test structure of the body object. 
Lets say it contains fields like "year", "month" etc. (or whatever the function returns)

2023-09-27 10:12 UTC, Bedkow commented on module-4/src/e2e.test.ts
> +	describe("/IsTodayPublicHoliday/DE", () => {
added to my to-read list ;)

2023-09-27 11:38 UTC, Bedkow commented on module-4/src/helpers.test.ts
> +	it("shortens public holiday entry", () => {
The function is not really written to handle those kind of situations. I know it is limited but it's not in the scope of this chapter for me to correct the course creators' code. I'll keep this regard in mind though. Thanks

2023-09-28 08:18 UTC, merged